services:
  catalogmanager.datacontainer.catalog:
    class: Alnv\ContaoCatalogManagerBundle\DataContainer\Catalog
    public: true
  catalogmanager.datacontainer.catalogfield:
    class: Alnv\ContaoCatalogManagerBundle\DataContainer\CatalogField
    public: true
  catalogmanager.datacontainer.catalogoption:
    class: Alnv\ContaoCatalogManagerBundle\DataContainer\CatalogOption
    public: true
  catalogmanager.datacontainer.module:
    class: Alnv\ContaoCatalogManagerBundle\DataContainer\Module
    public: true
  catalogmanager.hooks.initialize:
    class: Alnv\ContaoCatalogManagerBundle\Hooks\Initialize
    public: true
  catalogmanager.hooks.datacontainer:
      class: Alnv\ContaoCatalogManagerBundle\Hooks\DataContainer
      public: true