services:
  catalogmanager.datacontainer.catalog:
    class: Alnv\ContaoCatalogManagerBundle\DataContainer\Catalog
    public: true
  catalogmanager.hooks.initialize:
    class: Alnv\ContaoCatalogManagerBundle\Hooks\Initialize
    public: true