services:
  _defaults:
    autowire: true
    autoconfigure: true

  Alnv\ContaoCatalogManagerBundle\Controller\FrontendController:
    public: true

  catalogmanager.hooks.widget:
    class: Alnv\ContaoCatalogManagerBundle\Hooks\Widget
    public: true

  catalogmanager.datacontainer.catalog:
    class: Alnv\ContaoCatalogManagerBundle\DataContainer\Catalog
    public: true

  catalogmanager.datacontainer.catalogfield:
    class: Alnv\ContaoCatalogManagerBundle\DataContainer\CatalogField
    public: true

  catalogmanager.datacontainer.catalogoption:
    class: Alnv\ContaoCatalogManagerBundle\DataContainer\CatalogOption
    public: true

  catalogmanager.hooks.sqlcompilecommands:
    class: Alnv\ContaoCatalogManagerBundle\Hooks\SqlCompileCommands
    public: true

  catalogmanager.datacontainer.module:
    class: Alnv\ContaoCatalogManagerBundle\DataContainer\Module
    public: true

  catalogmanager.datacontainer.catalogpalette:
    class: Alnv\ContaoCatalogManagerBundle\DataContainer\CatalogPalette
    public: true

  catalogmanager.hooks.initialize:
    class: Alnv\ContaoCatalogManagerBundle\Hooks\Initialize
    public: true

  catalogmanager.hooks.breadcrumb:
    class: Alnv\ContaoCatalogManagerBundle\Hooks\Breadcrumb
    public: true

  catalogmanager.hooks.pageLayout:
    class: Alnv\ContaoCatalogManagerBundle\Hooks\PageLayout
    public: true

  catalogmanager.hooks.article:
    class: Alnv\ContaoCatalogManagerBundle\Hooks\Article
    public: true

  catalogmanager.hooks.datacontainer:
    class: Alnv\ContaoCatalogManagerBundle\Hooks\DataContainer
    public: true

  catalogmanager.hooks.element:
    class: Alnv\ContaoCatalogManagerBundle\Hooks\Element
    public: true

  catalogmanager.hooks.search:
    class: Alnv\ContaoCatalogManagerBundle\Hooks\Search
    public: true

  catalogmanager.hooks.formfields:
    class: Alnv\ContaoCatalogManagerBundle\Hooks\FormFields
    public: true